# Generated by Django 3.0.7 on 2020-06-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='in case if missed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='amount_of_upvotes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
